"""add tables colab_roles, colabs, event_colabs(esse sem a foreignkey para event, por enquanto)

Revision ID: 01179b8f3e41
Revises: c07ae6298be8
Create Date: 2024-10-09 09:37:00.303284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01179b8f3e41'
down_revision = 'c07ae6298be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colab_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('event_colabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('colab_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colab_id'], ['colabs.id'], ),
    sa.ForeignKeyConstraint(['role'], ['colab_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_colabs')
    op.drop_table('colabs')
    op.drop_table('colab_roles')
    # ### end Alembic commands ###
