"""adicionando coluna slug aos eventos

Revision ID: 167dccec6066
Revises: f4b1d3403078
Create Date: 2024-10-17 10:10:49.181216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167dccec6066'
down_revision = 'f4b1d3403078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=60), nullable=False))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
