"""adicionando coluna is_coor à tabela colabs

Revision ID: 4956718cf0e0
Revises: c8df9f7fdbbc
Create Date: 2024-10-21 21:16:07.527096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4956718cf0e0'
down_revision = 'c8df9f7fdbbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colabs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_coor', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colabs', schema=None) as batch_op:
        batch_op.drop_column('is_coor')

    # ### end Alembic commands ###
