"""alterando coluna desc da tabela sub_events de varchar(255) para text(500)

Revision ID: 8cb2c243ba88
Revises: c934b4f6da81
Create Date: 2024-10-25 16:55:25.730812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cb2c243ba88'
down_revision = 'c934b4f6da81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_events', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_events', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=sa.Text(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
