"""adicionado cascade à event_id no sub_events, para quando um evento for excluido

Revision ID: 9eeb6f8b5883
Revises: 8cb2c243ba88
Create Date: 2024-10-26 12:19:53.455443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eeb6f8b5883'
down_revision = '8cb2c243ba88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_events', schema=None) as batch_op:
        batch_op.drop_constraint('sub_events_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sub_events_ibfk_1', 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###
