"""criando tabela colab_areas e adicionando coluna area à tabela colab_event

Revision ID: c8df9f7fdbbc
Revises: 23912808b8d4
Create Date: 2024-10-17 15:48:52.278827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8df9f7fdbbc'
down_revision = '23912808b8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colab_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('event_colabs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'colab_areas', ['area'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_colabs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('area')

    op.drop_table('colab_areas')
    # ### end Alembic commands ###
