"""adicionando coluna permission_level à tabela colab_roles

Revision ID: c934b4f6da81
Revises: f4215d955cda
Create Date: 2024-10-24 14:48:21.670943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c934b4f6da81'
down_revision = 'f4215d955cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colab_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission_level', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['permission_level'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colab_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('permission_level')

    # ### end Alembic commands ###
