"""adicionando tabela para espectadores de um sub_evento

Revision ID: d732e7c159a6
Revises: 9eeb6f8b5883
Create Date: 2024-11-02 15:48:04.321133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd732e7c159a6'
down_revision = '9eeb6f8b5883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_event_viewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sub_event_id'], ['sub_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_event_id', 'user_id', name='user_already_in_this_sub_event')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_event_viewers')
    # ### end Alembic commands ###
