"""empty message

Revision ID: f4215d955cda
Revises: 276b3a5b9e48
Create Date: 2024-10-22 18:04:01.824527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4215d955cda'
down_revision = '276b3a5b9e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
