"""removendo coluna matricula de profiles

Revision ID: f4b1d3403078
Revises: a6bb30323a2c
Create Date: 2024-10-16 18:45:38.633316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4b1d3403078'
down_revision = 'a6bb30323a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('matricula')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matricula', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
